### ISSUE TITLE
[115 ESR] general.useragent.override will hang youtube.com

### ISSUE THREAD

**Issue by ghost** [Eclipse-Community/r3dfox-old#101]
And the browser will become not responding, too.

**Comment by the-r3dacted** [comment]
32 or 64 bit and what useragent?

**Comment by ghost** [comment]
> 32 or 64 bit and what useragent?

Windows 8.1 64 bit, r3dfox 64 bit.

It seems it will trigger when `general.useragent.override` is set regardless of what the user agent string is.

**Comment by the-r3dacted** [comment]
idk works for me
![ScreenShot_20240701130957](https://github.com/Eclipse-Community/r3dfox/assets/77039240/f0786693-6d1a-4f1d-b139-de73fb001f10)
![ScreenShot_20240701130914](https://github.com/Eclipse-Community/r3dfox/assets/77039240/06aa97cf-0976-4d22-91a4-fd93e2ce2067)

**Comment by ghost** [comment]
Your Windows 8.1 looks weird compared to mine. How do you have a dark theme?

Btw, the default user agent string of the browser is strange. I'm running on Windows 8.1, but it reports NT 6.2 (which is Windows 8). It also has `r3dfox/115.13.0` appended into the user agent string (which 127.0.0.2 doesn't have).

p/s: YouTube always hangs when loading `fonts.gstatic.com`.

**Comment by ghost** [comment]
Btw, the reason why I asked for 115 ESR is because this is the Firefox version I used before I decided to switch to r3dfox. I think it's best for me to continue with the 115 ESR series. But I decided to test 127.0.0.2, too. It works very well. I have no problem switching to 127.0.0.2. I'm sorry for wasting your time and effort with the 115 ESR series.

**Comment by the-r3dacted** [comment]
> Your Windows 8.1 looks weird compared to mine. How do you have a dark theme?

I tried experimenting with classic theme on 8.1 in a VM.  I did it in the most jank way possible, but it turned out kinda good. Good enough that I ended up doing it on my main. All the files are here. https://files.catbox.moe/wcidmm.7z

> I'm running on Windows 8.1, but it reports NT 6.2

I realize that this is because I messed up the manifest files. (I forgot to rename to r3dfox_esr) It should be fixed next release and report as 8.1

> It also has `r3dfox/115.13.0` appended into the user agent string (which 127.0.0.2 doesn't have).

Yeah, I want to try adding r3dfox back to the useragent. I started with 115 as I built that first after I made the change. I think I'll skip 127.0.3 and just do it in 128.0.

> I'm sorry for wasting your time and effort with the 115 ESR series.

If it's a bug as serious as this for something still supported, I would want to fix it. However if I can't reproduce, then I can't do much.
