### ISSUE TITLE
Figure out why 129 does not need zIndex/IsResizingNativeWidget and backport to 128 (ESR)

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#144]
This would remove a lot of mostly dead code in 128 and probably boost performance. In 128, if I remove IsResizingNativeWidget, context menus on Windows 7 without DWM break, however 129 is completely fine.

**Comment by marty60** [comment]
Unrelated to the bug but I'm glad to hear that you will be releasing 128esr versions. 

Will they specifically say for example 128.1esr 7+ (next week's official firefox release). I'm asking because you have several releases such as 128.0.3 Vista+ but I'll be looking for the 128esr 7+ releases to download.

**Comment by the-r3dacted** [comment]
They will all be Vista+ because why not?

If there's an issue caused by Vista support, lemme know, and I'll look into it.
