### ISSUE TITLE
[help] How to identify the differences between the code of R3dFox and vanilla Firefox?

### ISSUE THREAD

**Issue by Sevoos** [Eclipse-Community/r3dfox-old#210]
I probably don't know all the features of git, but it'd be nice to be able to perform the code modifications and build the browser manually.

**Comment by the-r3dacted** [comment]
https://github.com/mozilla/gecko-dev/compare/release...Eclipse-Community:r3dfox:release

Disable winlauncher but keep pbproxy starts the Vista compatibility changes.

Add back nsIFormControlFrame and nsITextControlFrame starts the browser style changes to get Aero/native controls working.

Download icons from 68 with r3d starts the functionality customizations on top of base Firefox. I should probably combine this with the r3dfox theme and settings commit, as it's more of a theme thing and I've tried to keep everything generic up until Mozconfigs. I'll probably do that in 133 which means classic about:config from nara would start it there.

Mozconfigs starts the changes that turn the the browser into being r3dfox instead of the generic Nightly name..

Any new issues that occur with the browser are at the end, until next version when I merge and reorder the commits to be in their respective category.
