### ISSUE TITLE
Broken UI on Windows 8.1

### ISSUE THREAD

**Issue by wealstarr** [Eclipse-Community/r3dfox-old#24]
Hello,

The newest release published [Beta v123.0.2-3](https://github.com/Eclipse-Community/r3dfox/releases/tag/123.0.2-3-beta) has title bar completely removed which creates visual artifacts on Windows 8.1, not only does the non-focused tabs are unreadable but also dark mode in the browser doesn't confirm to the design logic.  

Here's a screenshot:
![Capture](https://github.com/Eclipse-Community/r3dfox/assets/26643729/65087f3d-cde3-4339-b580-91f62ac2fcc4)

I followed the thread about broken Aero captions bar on Windows 7 but removing entire title bar makes it impossible to use on Windows 8 and above. Is there a possibility that we could revert to previous arrangement and get the title bar back ?

Kind regards

**Comment by the-r3dacted** [comment]
I have tested on both stock 8.1 and themed 8.1. Both are fine as far as I can tell.

Your theme seems to be a bit busted because the accent color should show. However I do need to fix inactive tabs having white text sometime.

Closing since kinda a duplicate of https://github.com/Eclipse-Community/r3dfox/issues/20

"Need to force inactive tab text to be black under 8.1."
