### ISSUE TITLE
Exception Breakpoint error

### ISSUE THREAD

**Issue by wealstarr** [Eclipse-Community/r3dfox-old#25]
Hello,

The newest release [Beta v123.0.2-3](https://github.com/Eclipse-Community/r3dfox/releases/tag/123.0.2-3-beta) throws exception breakpoint has reached error randomly and asks to restart r3dfox but when I click ok nothing happens and browser continue to work. This error pops up randomly every 5/10 minutes.

Screenshot:
![Capture2](https://github.com/Eclipse-Community/r3dfox/assets/26643729/3eda24de-71f8-41b4-97ab-2f1b4dbf0253)

Please note: this does NOT happen on version 122.

Kind regards

**Comment by the-r3dacted** [comment]
It's already hard enough to diagnose issues when I can reproduce them.

I will keep this open, but I'm fairly certain it's something you did to the system going by that you seem to have a theme, and I'm using r3dfox on 8.1 right now with no issues.

The only other thing I can think of is GPU acceleration since that was an issue under 7 and I fixed it in a later 123 release. Maybe try the version before the webrender fix. I run without GPU acceleration, things get very broken if I do due to my kinda weird GPU setup.

**Comment by wealstarr** [comment]
Thank you for the response. I'm using stock 8.1 and the theme is Windows 10 theme I ported myself for 8.1

This issue does not occurs on version 122 so something changed between 122 and 123. Maybe it's GPU, I'll try again when you post a new version provided that title bar is present like in 122.

**Comment by the-r3dacted** [comment]
124 isn't finished, but they went ahead and built a 124 portable release, so might as well try it I guess.

https://github.com/adeii/supermium-portable/releases/download/F1235/R3dfox-portable-win32-124.0-24.7z

**Comment by wealstarr** [comment]
Thanks, this error doesn't occur in version 124 but it has no title bar and context menu (right click menu) is very broad. I'll stick to 122. 

Kind regards
