### ISSUE TITLE
On Windows 7, r3dfox produces a VCRUNTIME140_1.dll error

### ISSUE THREAD

**Issue by DellM-79** [Eclipse-Community/r3dfox-old#32]
I tried installing r3dfox on my dad's old PC with Windows 7, but all I could get us a VCRUNTIME140_1.dll error. What causes that issue??

Specs:
OS: Windows 7 Ultimate (SP1) x64
Motherboard: MSI G31TM-P21
CPU: Intel Pentium E2200 (Conroe)
RAM: 2 GB
Hard Drive: 1 TB SSD

**Comment by the-r3dacted** [comment]
Firefox used to ship with VC++ dlls, but removed them when they dropped 7. I didn't add back since you kinda need them to use most programs and you should install VC++.

https://github.com/abbodi1406/vcredist/releases

**Comment by rovickti** [comment]
> Firefox used to ship with VC++ dlls, but removed them when they dropped 7

The whole visual studio redistributable mess creates it's own dll hell.

Mozilla had a lot of issues with not packaging the dlls for older operating systems, and decided to just include them it seems:

https://bugzilla.mozilla.org/show_bug.cgi?id=1624546#c2
> The way this works has always been a maintenance nightmare forever. I think what is really needed is to trust that the builder has the correct runtime routines in the redist dir and just to make sure any file matching any of the following patterns gets packaged:

> vcruntime[0-9]+.dll
> vcruntime[0-9]+[0-9]+.dll
> msvcp[0-9]+.dll
> msvcp[0-9]+[0-9]+.dll

People struggle with the whole find, download, find the file, and run the redistributable installer thing.It's unintuitive these days as people become reliant on the windows updater or digital software stores to install everything at a click. So it would probably cause more support requests, with the majority giving up before asking.
https://bugzilla.mozilla.org/show_bug.cgi?id=1691782

The correct solution, to avoid conflicts in different versions of the same visual studio redistributable version, is apparently to uninstall all redistributables, and then install the very latest versions. Some websites just provide the latest/last versions of every single redistributable in one package to fix Microsoft's redistributable hell:
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

----

Alternative to packaging:
Include the redistributable in the installer and have it run at the cost of file size, and possibly more installer maintenance?

Maybe having an error message that told users what to download, and possibly where to download it, might help. Users would need to understand the difference between x64/x86/arm64, so that would have to be mentioned as well:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

----

Ideally, Mozilla should just not depend on Microsoft. Microsoft will eventually stop creating redistributables compatible with old operating systems, like they did with XP. If Mozilla created a non-Microsoft project for Windows, they could use a non-Microsoft compiler (e.g. GCC/mingw) for release builds, bundle dll dependencies, and possibly get faster performance.

**Comment by the-r3dacted** [comment]
You can compile with mingw32, even compile with it from Linux. However performance is worse.

I'm not shipping them because you really should just have them by now.
