### ISSUE TITLE
Hardware Acceleration (GPU)

### ISSUE THREAD

**Issue by PARAViRTUALiZATiON** [Eclipse-Community/r3dfox-old#34]
* Hardware Acceleration (GPU) does not work correctly when playback Video-Content

**Comment by jonm58** [comment]
What is your PC configuration?
What's your version of Windows?

**Comment by PARAViRTUALiZATiON** [comment]
[Intel® UHD Graphics 630](https://www.intel.de/content/www/de/de/support/products/126790/graphics/processor-graphics/intel-uhd-graphics-family/intel-uhd-graphics-630.html)
* Windows**⁷**

**Comment by the-r3dacted** [comment]
I have no UHD 630 computers. Unrelated to the issue I would've gotten a mini PC with UHD 630 had I not gotten scammed and shipped a 4th gen PC instead but whatever. I can't test, and I know it's fine on AMD/Nvidia so I'm assuming wacky modded Intel drivers.

**Comment by PARAViRTUALiZATiON** [comment]
In any case, Mozilla Firefox **(**115.9.1 ESR | 116.0.3**)** seems to be able to use (GPU) Hardware-Acceleration.

**Comment by jonm58** [comment]
> In any case, Mozilla Firefox **(115.9.1 ESR | 116.0.3)** seems to be able to use (GPU) Hardware-Acceleration.

so?Hardware Acceleration (GPU) work correctly when playback Video-Content in Mozilla Firefox (115.9.1 ESR | 116.0.3)?
Check Hardware Acceleration at about:support

**Comment by PARAViRTUALiZATiON** [comment]
* Done:

Everything looks fine, so there must be another Background, why the CPU-Utilization from **[r3dactedfox](https://github.com/Eclipse-Community/r3dfox)** is higher by Comparison.

**Comment by garry-ut99** [comment]
Maybe also try to compare:
- Firefox 115 ESR vs R3dfox 122/123 on Win 7 (I assume you already compared to R3dfox 124)
- Firefox 122 vs R3dfox 122 on Win 10 (if you have access to Win 10 PC)
- Firefox 124 vs R3dfox 124 on Win 10 (if you have access to Win 10 PC)

At least that will tell which versions of Windows and Fox are affected

**Comment by the-r3dacted** [comment]
This should be fixed in latest 124 and 125. I forgot this issue existed.

**Comment by garry-ut99** [comment]
OP didn't specify which codecs he has been reporting as broken (H264 ?)

Chrome and Firefox (on Desktop) officialy support VP9 / H265 / AV1 hardware decoding only in Windows 10  / 11 
(also as for H265, it isn't supported at all in Firefox due to licence problems). I have in about:support in both Firefox 115.9 ESR and R3dfox 125.0.2: `H264: HW, HEVC: SW, AV1: SW`.

But hardware decoding  in VP9 / H265 / AV1 works fine in Win 7 SP1 in desktop players like [VLC media player]( https://www.videolan.org/vlc/index.pl.html) or [MPC-HC](https://github.com/clsid2/mpc-hc) (althought it required some 3rd-party codecs to be installed manually in Win 7) so it's technically possible to be implemented into R3dfox - also a similiar issue / request has been reported to Supremium issue tracker:
- https://github.com/win32ss/supermium/issues/146
