### ISSUE TITLE
Native scroll bar and other elements

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#4]
Edit: Splitting native or Aero caption bar into a new issue.

This would be a nice to have, however I am not going to look into it as it's not really something I need. It would be cool to have, but I can live without it.

If you want it, you can pull request it.

**Comment by wealstarr** [comment]
I'm not sure I understand what you mean, but I assume you're referring to the custom caption/title bar build in Firefox, not the one used by Microsoft. If that's so, please I urge you to let it be this way as the windows caption bar in browser creates lots of issues for Windows7/8.1 users as they don't have dark mode and still want to use the dark colors in browsers. It destroys the entire design logic. I don't know whose genius idea was it to remove the custom caption bar and use the one from Windows but at least they got it right now we, the users of Windows 7 can now use the newer browsers again, thanks to you.

Please leave the captions bar be. My only issue with it is that it's way too broad, if we have a way to slim it any further.

Regards

**Comment by the-r3dacted** [comment]
> I'm not sure I understand what you mean, but I assume you're referring to the custom caption/title bar build in Firefox, not the one used by Microsoft. If that's so, please I urge you to let it be this way as the windows caption bar in browser creates lots of issues for Windows7/8.1 users as they don't have dark mode and still want to use the dark colors in browsers. It destroys the entire design logic. I don't know whose genius idea was it to remove the custom caption bar and use the one from Windows but at least they got it right now we, the users of Windows 7 can now use the newer browsers again, thanks to you.
> 
> Please leave the captions bar be. My only issue with it is that it's way too broad, if we have a way to slim it any further.
> 
> Regards

What I know is that the title bar in 117+ looks like the Windows 10 title bar no matter what OS it's run on. I want to fix that.

**Comment by wealstarr** [comment]
> > I'm not sure I understand what you mean, but I assume you're referring to the custom caption/title bar build in Firefox, not the one used by Microsoft. If that's so, please I urge you to let it be this way as the windows caption bar in browser creates lots of issues for Windows7/8.1 users as they don't have dark mode and still want to use the dark colors in browsers. It destroys the entire design logic. I don't know whose genius idea was it to remove the custom caption bar and use the one from Windows but at least they got it right now we, the users of Windows 7 can now use the newer browsers again, thanks to you.
> > Please leave the captions bar be. My only issue with it is that it's way too broad, if we have a way to slim it any further.
> > Regards
> 
> What I know is that the title bar in 117+ looks like the Windows 10 title bar no matter what OS it's run on. I want to fix that.

Fix it by all means, I welcome it, you might wanna look at this project:
https://github.com/black7375/Firefox-UI-Fix

All I'm saying just don't use the captions bar from Windows as when browser is in dark mode it creates weird visual artifact because Windows 7 and 8.1 doesn't have dark mode so users end up with light caption bar, dark tabs and dark everything else that looks weird. Of course it takes years for the genisus at Google and Mozilla to figure this out. Now that it's finally fixed, We don't wanna make this mistake again.

**Comment by NoNameNeeded5** [comment]
I don't really understand what the problem is...
Yes, Firefox comes with a fake Windows 10 caption bar, but no one has to use that.
When you go to the customize page, you can choose to use the native title bar instead, which looks like this (if you use the classic theme in Windows 7)

![ScreenShot 837](https://github.com/Eclipse-Community/r3dfox/assets/149444732/250fc05f-8081-4aee-b40a-edd8f598e37d)

When you select dark mode, it looks like this:

![ScreenShot 839](https://github.com/Eclipse-Community/r3dfox/assets/149444732/cfb98c1d-e448-4a1a-a122-bf04827aa7d8)

Ok, I'll admit that the upper part of the browser doesn't look that dark (some would even say it's very light) but the actual "website-part" is dark enough in my book...

**Comment by the-r3dacted** [comment]
I don't mean like that, I mean like having aero on the tab part.

**Comment by NoNameNeeded5** [comment]
Oh, now I get it.

Well yeah, that's just the way it is. Mozilla replaced more and more of the native stuff with fake Windows 10 bars and caption bars and context menus and scroll bars etc.

Makes no sense whatsoever because on Windows 10 you have all the Windows 10 stuff anyway, so you wouldn't need fake stuff and on other OSes you probably don't want fake Windows 10 stuff but that's just the way it is...

I even asked the guys from Waterfox if they could retain the native scrollbars in their browser but they didn't.

There is something for Firefox that will bring back native scrollbars and other stuff.
However it's not a complete browser but just one dll file that only works in Firefox ESR 115, so it should work on Windows 7 too.
(but that has nothing to do with Redfox)

https://github.com/ephemeralViolette/firefox-native-controls/releases

**Comment by NoNameNeeded5** [comment]
P.S. I just tried this with the modified xul.dll (in Firefox 115 ESR 64Bit) on Windows 7 and it seems to work.
Native scrollbars and also the native caption and title bar.

(but as I said, it has nothing to do with Redfox)

**Comment by the-r3dacted** [comment]
Yeah 122-fucked branch was my first attempt and it's 95% there, but I want to restart and do it a bit more cleanly. I think caption bars will come next release, unless there's some issue I can quickly fix, it should be there. Scroll bars may also come or they could be later idk.

**Comment by the-r3dacted** [comment]
Everything should be in 124.0.2-aero

https://github.com/Eclipse-Community/r3dfox/releases/tag/124.0.2-aero

Report any issues with native elements in https://github.com/Eclipse-Community/r3dfox/issues/37

**Comment by NoNameNeeded5** [comment]
It doesn't work on Win Server 2008 R2 (which is the server version of Windows 7)
There is an error when you install it, something with a missing entry point or something (EventSetInformation) in Advapi32.dll and then when you try to start Redfox there is an XPCOm error.
I assume it won't work on Windows 7 either, even though I can't test it right now.

**Comment by jonm58** [comment]
> It doesn't work on Win Server 2008 R2 (which is the server version of Windows 7) There is an error when you install it, something with a missing entry point or something (EventSetInformation) in Advapi32.dll and then when you try to start Redfox there is an XPCOm error. I assume it won't work on Windows 7 either, even though I can't test it right now.

try this
https://www.catalog.update.microsoft.com/Search.aspx?q=KB3080149

**Comment by NoNameNeeded5** [comment]
Ok, it works now.
How did you know which update fixes that problem?

**Comment by the-r3dacted** [comment]
I know there's some other update that is less sus that adds it, but I have no idea what it is. My W7 has it without KB3080149.
